apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-project
  template:
    metadata:
      labels:
        app: mlops-project
    spec:
      containers:
      - name: mlops-project
        image: your-dockerhub-username/mlops-project:latest
        ports:
        - containerPort: 5000